export enum RuleId {
  ShowArcaneSimultaneous = 1,
  ChooseAction,
  PlaceArcane,
  MoveSpirit,
  PrepareNextRound,
  TakeSpiritCards,
  EndOfRoundSpiritCardsUnderDeck,
  EndOfRoundRotateArcaneInCards0,
  EndOfRoundRotateArcaneInCards1,
  EndOfRoundRotateArcaneInCards2,
  EndOfRoundResolveGrove0,
  EndOfRoundResolveGrove1,
  EndOfRoundResolveGrove2,
  EndOfRoundTakeElderSpirit0,
  EndOfRoundTakeElderSpirit1,
  EndOfRoundTakeElderSpirit2,
  ElderEffectPlaceCardUnderDeckInGrove,
  ElderEffectShowArcane,
  ElderEffectTakeSpirit,
}
