export enum LocationType {
  PlayerDeck = 1,
  PlayerDruid,
  PlayerHand,
  GrovesRiver,
  FoxEliteCardsDeck,
  FoxEliteCard,
  BearEliteCardsDeck,
  BearEliteCard,
  OwlEliteCardsDeck,
  OwlEliteCard,
  ArcaneReserve,
  ElderSpiritCardsDeck,
  ElderSpiritCardsRiver,
  RoundCard,
  RoundPiste,
  GroveMajority,
  ArcaneShowLayout,
  PlayerSpiritUnderGroveLayout,
  PlayerSpiritNearDruidLayout,
  ArcaneOnSpiritCardLayout,
  ArcaneDiscard
}
